### ISSUE TITLE
Vort Plugin Issues

### ISSUE THREAD

**Issue by ReckerXF** [JohnyReaper/johny-helix-plugins#1]
The Vort Beam entity does not work because you are using incorrect commenting. Lua does not use double slashes, but instead double dashes. For multi-line commenting do

`--[[
print("Multi-Line Comment")

]]--`

**Comment by JohnyReaper** [comment]
The problem you are talking about is caused by something other than bad commenting. GLua allows you to use // and -- for commenting. And if you are talking about multi-line commenting then you can use /* */ as well
